### ISSUE TITLE
Actuator API

### ISSUE THREAD

**Issue by mitra42** [mitra42/frugal-iot#6]
Top level for actuators - which is basically anything it does from blinking LED, to outputing on pins, to switching a relay

- [x] Define actuator API 
- [x] Review ESPHOME to see if can use
- [x] Think through configuration issues

### Template for each actuator

- [x] Obtain example(s)
- [x] Build simple interface
- [x] Consider if can redesign frugal to direct attach to pin
- [x] Consider configuration and add to _settings.h
- [x] Document

**Comment by mitra42** [comment]
Blinken is added, and compiled, but not yet tested on a board.

**Comment by janandrzejewski** [comment]
I tested on my Arduino Uno. It worked fine

**Comment by mitra42** [comment]
Thanks for visiting - its just the beginning of the project, and always happy to get suggestions.

**Comment by mitra42** [comment]
Closing - got a couple of examples of digital actuators now
